baseURL = "https://mngb.github.io/notes"
languageCode = "en-us"
title = "Redef 的笔记"
theme = "PaperMod"

# relativeURLs = true
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowReadingTime = true
ShowToc = true
TocOpen = true
ShowCodeCopyButtons = true
comments = true
ShowShareButtons = true
# disableSpecial1stPost: true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
  
[params.profileMode]
enabled = true
title = "Redef 的笔记"
subtitle = "使用 Emacs + Org-Roam 编写"
imageUrl = "<image link>"
imageTitle = "<title of image as alt>"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10
